### ISSUE TITLE
"Applications will snitch on you"

### ISSUE THREAD

**Issue by BT5U** [epidemics-scepticism/tor-misconception#1]
why doesnt github have a private message system, really. whats the best way to contact you? this was a great read by the way. so, how can i keep my rss desktop client from snitching when it fetches all those feeds through tor??

**Comment by epidemics-scepticism** [comment]
[Tails](https://labs.riseup.net/code/issues/11399) and [Tor Birdy](https://trac.torproject.org/projects/tor/ticket/19031) are looking to get the Tor Birdy addon to do RSS reading. Currently Tails uses Liferea but [they're looking to drop it](https://labs.riseup.net/code/issues/11082). My email is normally in the copyright notice on my code, my email address is also my XMPP address. I don't maintain a long-term OTR or PGP key currently.
